# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qDescription', models.CharField(max_length=200)),
                ('qTag1', models.CharField(max_length=30)),
                ('qTime', models.IntegerField(default=0)),
                ('qAnonymous', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qName', models.CharField(max_length=30)),
                ('qQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaq.Question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='qQuestions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaq.Question'),
        ),
    ]
