# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaq', '0002_auto_20161223_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qidd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uidd', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='qName',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='qQuestion',
        ),
        migrations.AddField(
            model_name='option',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tName',
            field=models.CharField(default='no_tag', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='qDescription',
            field=models.CharField(default='no_name', max_length=200),
        ),
        migrations.AddField(
            model_name='usedq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaq.User'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='qaq.User'),
        ),
    ]
