# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaq', '0003_auto_20161228_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
