# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaq', '0004_question_concluded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='qQuestions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qDescription',
        ),
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.CharField(default=b'no_id', max_length=200),
        ),
        migrations.AlterField(
            model_name='usedq',
            name='qidd',
            field=models.CharField(default=b'no_q', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='uidd',
            field=models.CharField(default=b'not_valid', max_length=200),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
